# Generated by Django 5.2.4 on 2025-08-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0004_alter_stop_img_alter_stop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.IntegerField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_end', to='mainapp.stop')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_start', to='mainapp.stop')),
            ],
        ),
    ]
