# Generated by Django 5.2.4 on 2025-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusRoute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
