# Generated by Django 5.2.4 on 2025-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='buss/')),
                ('reg_no', models.CharField(max_length=10)),
                ('no_of_seats', models.IntegerField(default=40)),
            ],
        ),
    ]
