# Generated by Django 5.2.4 on 2025-08-11 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
