# Generated by Django 5.2.4 on 2025-08-12 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_bus_no_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='reg_no',
            field=models.CharField(max_length=17, validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
