# Generated by Django 5.2.4 on 2025-08-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_bus_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='reg_no',
            field=models.CharField(max_length=17),
        ),
    ]
