# Generated by Django 5.2.4 on 2025-08-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusRoute', '0002_busroute_price'),
        ('bus', '0004_alter_bus_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('busroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusRoute.busroute')),
            ],
        ),
    ]
