# Generated by Django 5.2.4 on 2025-08-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
    ]
