# Generated by Django 5.2.4 on 2025-08-22 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_remove_schedule_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 11, 43, 18, 788713, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
