# Generated by Django 5.2.4 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('long', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lati', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
    ]
