# Generated by Django 5.2.4 on 2025-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_stop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='img',
            field=models.ImageField(default='', null=True, upload_to='stops/'),
        ),
    ]
