# Generated by Django 5.2.4 on 2025-08-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
        ('mainapp', '0004_alter_stop_img_alter_stop_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('end_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_end', to='mainapp.stop')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.schedule')),
                ('start_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_start', to='mainapp.stop')),
            ],
        ),
    ]
