# Generated by Django 5.2.4 on 2025-08-20 09:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_ticket_passengers_ticket_status_alter_ticket_amount'),
        ('mainapp', '0004_alter_stop_img_alter_stop_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='end_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 20, 9, 48, 43, 119313, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_end_stop', to='mainapp.stop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_start_stop', to='mainapp.stop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
