# Generated by Django 5.2.4 on 2025-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_rename_schedule_id_ticket_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
