# Generated by Django 5.2.4 on 2025-08-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start',
        ),
    ]
