# Generated by Django 5.2.4 on 2025-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_remove_ticket_end_remove_ticket_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
