# Generated by Django 5.2.4 on 2025-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passengers',
            field=models.ManyToManyField(related_name='tickets', to='Ticket.passenger'),
        ),
    ]
